name: Check Version Upgrade

on:
  push:
    branches-ignore:
      - master

jobs:
  check-version:
    name: Check Version Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch-tags
        run: git fetch --tags origin
      - name: fetch-versions
        run: |
          echo "PAST_VERSION=$(git describe --prune --unshallow --tags --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: check-versions
        if: ${{ env.NEW_VERSION == env.PAST_VERSION }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('expected a version upgrade')
