name: Check Version Upgrade

on:
  push:
    branches-ignore:
      - master

jobs:
  get-versions:
    name: Check Version Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch-tags
        run: git fetch --prune --unshallow --tags origin
      - name: fetch-versions
        run: |
          echo "PAST_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(cat VERSION)" >> $GITHUB_ENV
  check-versions:
    name: check-versions
    runs-on: ubuntu-latest
    if: ${{ env.NEW_VERSION }} == ${{ env.PAST_VERSION }}
    steps:
      - name: check-versions
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('expected a version upgrade')
