name: Check Version Upgrade

on:
  push:
    branches-ignore:
      - master

jobs:
  check-version:
    name: Check Version Upgrade
    runs-on: ubuntu-latest
    if: ${{ (cat VERSION) }} == ${{ (git describe --tags --abbrev=0) }}
    steps:
      - name: check-version
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('expected a version upgrade')