name: Check Version Upgrade

on:
  push:
    branches-ignore:
      - master

jobs:
  check-version:
    name: Check Version Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: fetch-versions
        id: step_one
        run: |
          echo "PAST_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: check-version
        if: ${{ env.NEW_VERSION }} == ${{ env.PAST_VERSION }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('expected a version upgrade')