name: Release

on:
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: version
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          prerelease: false
