name: Release

on:
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed

jobs:
  build_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: version
        run: cat VERSION
        id: version
      - name: release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          draft: false
          generate_release_notes: true
          name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          prerelease: false
