name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_tag:
    name: Create and Push Tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: version
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version
      - name: tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.version.outputs.version }} -m "${{ steps.version.outputs.version }}"
          git push origin v${{ steps.version.outputs.version }}
